(((lambda x (lambda y y)) 2) 1)
(((lambda (x) (lambda y y)) 2) 1)
(((lambda (x) (lambda (y) y)) 2) 1)
(((lambda x (lambda (y) y)) 2) 1)
(((lambda x (lambda (y) y))) 1)
(((lambda (x . y) (lambda () x)) 1))
(((lambda x (lambda () x)) 1))